# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "baron"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan Buggia"]
  s.date = "2013-03-07"
  s.description = "Hacked version of the toto blog engine."
  s.email = "nbuggia@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "LICENSE",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "lib/baron.rb",
    "spec/baron_article_spec.rb",
    "spec/baron_blog_engine_spec.rb",
    "spec/baron_spec.rb",
    "spec/sample_data/Gemfile",
    "spec/sample_data/Rakefile",
    "spec/sample_data/articles/2012-11-09-sample-post.txt",
    "spec/sample_data/articles/poems/1909-01-02-If.txt",
    "spec/sample_data/articles/poems/1916-01-01-the-road-not-taken.txt",
    "spec/sample_data/config.ru",
    "spec/sample_data/images/import-csv-file-1.png",
    "spec/sample_data/images/import-csv-file-2.png",
    "spec/sample_data/images/import-csv-file-3.png",
    "spec/sample_data/images/instagram.png",
    "spec/sample_data/pages/about.rhtml",
    "spec/sample_data/resources/feed.rss",
    "spec/sample_data/resources/redirects.txt",
    "spec/sample_data/resources/robots.txt",
    "spec/sample_data/themes/test/css/app.css",
    "spec/sample_data/themes/test/css/bootstrap-responsive.css",
    "spec/sample_data/themes/test/css/bootstrap-responsive.min.css",
    "spec/sample_data/themes/test/css/bootstrap.css",
    "spec/sample_data/themes/test/css/bootstrap.min.css",
    "spec/sample_data/themes/test/img/glyphicons-halflings-white.png",
    "spec/sample_data/themes/test/img/glyphicons-halflings.png",
    "spec/sample_data/themes/test/img/instagram.png",
    "spec/sample_data/themes/test/js/bootstrap.js",
    "spec/sample_data/themes/test/js/bootstrap.min.js",
    "spec/sample_data/themes/test/js/image_alt.js",
    "spec/sample_data/themes/test/js/read_later.js",
    "spec/sample_data/themes/test/templates/archives.rhtml",
    "spec/sample_data/themes/test/templates/article.rhtml",
    "spec/sample_data/themes/test/templates/category.rhtml",
    "spec/sample_data/themes/test/templates/error.rhtml",
    "spec/sample_data/themes/test/templates/index.rhtml",
    "spec/sample_data/themes/test/templates/layout.rhtml",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/nbuggia/baron"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Hacked version of the toto blog engine"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<rdiscount>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<rdiscount>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<rdiscount>, [">= 0"])
  end
end

